data = '''umdryebvlapkozostecnihjexg
amdryebalapkozfstwcnrhjqxg
umdcyebvlapaozfstwcnihjqgg
ymdryrbvlapkozfstwcuihjqxg
umdrsebvlapkozxstwcnihjqig
umdryibvlapkohfstwcnfhjqxg
umdryebvqapkozfatwcnihjqxs
umzrpebvlapkozfshwcnihjqxg
fmhryebvlapkozfstwckihjqxg
umdryebvlahkozfstwcnizjrxg
qmdryebvlapkozfslwcnihgqxg
umdiyebjlapknzfstwcnihjqxg
umdryebvlapkoqfstwcaihvqxg
cmdryebvlapkpzfstwcnihjvxg
umdryebvlakkozfstwcgihjixg
umdryebvlasjozfstwcnihqqxg
umdryebvladkozfsvwcnifjqxg
umdrlebvlapaozfstwcniwjqxg
umdryebvlhpkozrstwsnihjqxg
umdryebvcapkozfqtwcnihjrxg
ubdrykbvlapkowfstwcnihjqxg
umdryebvldpkozfstwcnihtqsg
umdryebvlapaozyutwcnihjqxg
umdryibvlapkozfstdfnihjqxg
umdryebvlapgozkstwznihjqxg
umdrxebvlapkozfstwcngxjqxg
umdryekvlapkozfstwclchjqxg
nmdryebvlapkozjsewcnihjqxg
umdryebvyapkozfstfcniheqxg
umdfyebvlapkozfstwcnhhjpxg
umdryelylupkozfstwcnihjqxg
smdryebvlqpkozfstwcnihjdxg
umdryebvlapaozfsuwcnihjqxc
umdryebvlrzkozrstwcnihjqxg
umdbycbvlapkojfstwcnihjqxg
umdryebvlapkonfstwpnirjqxg
uecryebvlapkozfstwcnihpqxg
uqdryebvltpkozfstwcnihrqxg
umdryebvlqsknzfstwcnihjqxg
cmdryebvlapkocfstwcvihjqxg
umdrkebvlapkozqsfwcnihjqxg
umdryabveapkoifstwcnihjqxg
ummrnehvlapkozfstwcnihjqxg
umdryebvlxpkozfstwqnihjtxg
umdryebvlagkozastwcnihjqxh
umdryebvlatkozzhtwcnihjqxg
umdryebvlcpkozfstwrnihjqvg
umdryebvlapkozfsnwcnrhjcxg
umdzyebvlypkozfstwcnibjqxg
nmdryebvlvpkozbstwcnihjqxg
uwdryebvlipkozfstwcnihvqxg
umdraebvlavkozfstwcnihjqwg
umdeyebvlspbozfstwcnihjqxg
umdryxlvlapkozfstwcnihjqxu
umdryegvlapkqzfstwcnirjqxg
umdrupbvlapkozfstwcnihjqog
imxryebvlapkxzfstwcnihjqxg
umdrfebvlapkozowtwcnihjqxg
umdreebvlapkozmstwczihjqxg
undryebdlapkozbstwcnihjqxg
umdryebvlapkpzfetwcnihjqxb
ymdnyebvlapkozfstwinihjqxg
umdryebvaapkozfstwcnihyqqg
umdryebvlapkzzwsrwcnihjqxg
umdrkebvlapkmzfskwcnihjqxg
umdrmebvlapkozfsvwcnidjqxg
umdlyehvlapkozfstwcnihjqkg
umnryebvlrpkozfstwjnihjqxg
uqdryebvlapxozfsawcnihjqxg
vmdruebvlapkozfstwcnihjqqg
umdryabviapkozistwcnihjqxg
umdryebvlapkzzfstwfnihkqxg
uvdryebvlapkozfsxwcuihjqxg
umdlhebvlapkozfstwcnvhjqxg
umdreebvlapkopfstjcnihjqxg
umdryebvlazkomfstwynihjqxg
kmdryebulapkoznstwcnihjqxg
umdryebvxakkozfstwinihjqxg
ukdryobvlapkozistwcnihjqxg
umdryebveapkozfstwcnthjqgg
mmdrtebvlapcozfstwcnihjqxg
umdryebvlapkolistwnnihjqxg
umdryebxlapkozfatwcnihjqxx
uxdryebvlapkozfstwhniheqxg
ufdryebvzapkozfstwcnbhjqxg
amdryhbvlapkozfstwcnifjqxg
umqryebvlaphozfstwcnihjqxn
umdryebvlapkosfstfcnihjqxe
gmkryebvlapkozfstwcnihjmxg
umdrnebvlkpkozfstwcnihjnxg
umdryebvrapkozfstmcndhjqxg
umdryebvmapkozfstichihjqxg
umdryesvnapkozestwcnihjqxg
umeryhbvlapkozfstfcnihjqxg
umdryedvbapkozfstwcnihqqxg
umdryebllapzozfstwcnihjvxg
umdcyebvlzdkozfstwcnihjqxg
umdrybbvlapkbvfstwcnihjqxg
umdrytbglapkozfsthcnihjqxg
umdryebvlkpkozfsteclihjqxg
umdntebvlapkmzfstwcnihjqxg
lkdryebveapkozfstwcnihjqxg
ymdryubvlapkozfstwbnihjqxg
tmrryebvlapkozfstwcnqhjqxg
umdryeovlaekonfstwcnihjqxg
umiryeuvlapkozfstwcnihjwxg
umdryebvlspvozwstwcnihjqxg
umdrtebvlapkoznxtwcnihjqxg
umvryebvlaphozfstwcnahjqxg
umdryebvlapkozfstinniajqxg
umdryebqlapkozfctwcnihjqxx
umdryebvlapkbzfptwcnihjqvg
umdryabviapkozistwcnihjqxd
umdryrbvlapkezfstscnihjqxg
umhryebvlapkozfstacnihxqxg
umdxyelvlapkozfitwcnihjqxg
umdryevvuapkozfstwcnihtqxg
uydrypbvxapkozfstwcnihjqxg
umdryebvlapkopfstwcnihzqxo
uedryebvlapkozistwceihjqxg
umdiyebvlapkozfgtwcnihjqxv
ymdryebvlapkozfsticniqjqxg
umbrkebvlapkozfslwcnihjqxg
umdryebliapkozbstwcnihjqxg
umvryebolapkozfstwcnihjqig
umdryeavbackozfstwcnihjqxg
umdryfbvlapsozfstwcnihaqxg
umdqyebvlapkozfjtgcnihjqxg
umdrjebvlaqkozfstwcyihjqxg
umdryebklaqkozrstwcnihjqxg
umdryebvpapkozfstwcpihjqjg
uydryebhlawkozfstwcnihjqxg
umdyyebvlapkozfstwcykhjqxg
umdryebvlapkozfstwcnitjnxh
umdzyebvlapkozfstwcnehyqxg
mmcryebvlapkozfstwinihjqxg
umdryebvlapuozfstwmvihjqxg
umdryfbvlapkozqstwcnihjmxg
umdryebslapsozfhtwcnihjqxg
umdtyemvlapmozfstwcnihjqxg
umdrxevvlapkozfytwcnihjqxg
umdahebvlapjozfstwcnihjqxg
umdryebvlapkozfstacnivjqxb
umdryebvlzpkozfjtwcnihjyxg
umdryebvlaqkozfstwcnisjqxu
umdrydbvlapkozfsuwcnihjlxg
umdryebvlapkomrstwcnihjqkg
umdryebvlapcozfstmcnwhjqxg
umdryebvlahkozfstwcibhjqxg
gmdrzebvlapkozlstwcnihjqxg
umdryebvlapkezfsswcnrhjqxg
umdryebvlapkoqfitwcgihjqxg
umdrnebvlapkozfsiwcninjqxg
umdryebvlapkozfsrwckohjqxg
umdryebtlapkomfstwcnihjexg
umdryxbvlapjozfstwcnihoqxg
umdpyebvlapkosustwcnihjqxg
umdryebvlapkvzfawwcnihjqxg
umhnyebvlaikozfstwcnihjqxg
umdryebvlagkozfstvknihjqxg
uodryebjlapkoxfstwcnihjqxg
umdryefdlapkozfstwcnyhjqxg
umprmebvtapkozfstwcnihjqxg
umdhyebvlapoozfstwcnihjqgg
uddryebvidpkozfstwcnihjqxg
umdryebtlapkozfetwfnihjqxg
umdbyebolapkozfstwcoihjqxg
umdryebvlapkonfstwcnihjpxo
umdryebvlapkohfstwcnihjqwk
umdryebolalkkzfstwcnihjqxg
updryebvxapkozfstwcnshjqxg
umdryebvlapkovfktwcnuhjqxg
umdrqrbvlppkozfstwcnihjqxg
umdrylgvlapkozfstwrnihjqxg
umdryebvlapkozfstxcnihbqig
uvdryeevlappozfstwcnihjqxg
zmdryebvlapkozfstwcnihqqxt
umdryebvlapvozfstwenihiqxg
umdryebvlbpkozfsgwcnihjlxg
umdryhbvlapkozfstwcnihtqxw
umdreecvlapkozwstwcnihjqxg
umwryebvlapkoztsmwcnihjqxg
ukdryebvfapkozrstwcnihjqxg
umdrylbdlamkozfstwcnihjqxg
umdryebvlapoozwsmwcnihjqxg
umdryebvlapkozfqtwcnnzjqxg
umdryekvlapktzfstwcnohjqxg
umdryebvlapkozfstwcnihjwqo
umdrrebflapkogfstwcnihjqxg
umdryevvlapkozfztwctihjqxg
umdrybbvlapkozfstwcnihxaxg
umdryebvlapkozfsowcnphjqag
smdryebvlapbozfitwcnihjqxg
umdryebvtapiozfstwcnihjqxe
umdryebjlakkozfstwccihjqxg
umdryebvlapdozfshwckihjqxg
umnryebvlapiozfstwcnihlqxg
umdrycbvlapkjzfsnwcnihjqxg
umdryebvyaprozjstwcnihjqxg
ucdryebvlapkozfstwomihjqxg
umdryebvlagklzfstwcnihjqyg
umdryebvladkozfstwcnihjqjh
umdrwebvlapkozfstwdnicjqxg
umdryebvlapkmzfstwcniheqxr
umdryebvlapkjzfstwcviheqxg
umdrvebvlapkozfstwcbihjqmg
umdrfebvlapkoffstwcnihsqxg
umdryebvtarkazfstwcnihjqxg
umdryebvlapkozfstwcfihjcng
umdryebvlapkktostwcnihjqxg
uedryeevlapkozfstwcniijqxg
bmdryebylapkozfstwcnihjqog
umdryebvlmpkoztstwcnihjqeg
umdryepvlarkohfstwcnihjqxg
uwdryebvlapklzfstzcnihjqxg
umdryebklapkozfsswcbihjqxg
umdtyeavlapkozfstwsnihjqxg
umdryebvaapkozfhtfcnihjqxg
umdrpebvlapuozfstwvnihjqxg
umdryebvlapkozffmwcniijqxg
uqdpyebvlapkozfstwfnihjqxg
umdryebvlapuozdstwcnihjhxg
tmdryhbvlapkozfptwcnihjqxg
umdryevvmapkozfstwcnihjgxg
umdryeuvlapmozfstwcnihjwxg
umdryebqlzpkozfbtwcnihjqxg
umdryebvsapkozystwcniqjqxg
imdryebvlapkozfscwinihjqxg
umdryebvlzpkozustwcnmhjqxg
umdrypbvlapbozfsnwcnihjqxg
bmdryebvlapqoznstwcnihjqxg
umdrfebvlapaozfstwcnihxqxg
umdiyebvxapkozfstwcnchjqxg
umdrygbvlapkozfstwcnizjqxz
amdryedvlapkozfstwcnihfqxg
umdryebvvapzozfstwcnihjgxg
undryebvlapkzzfstjcnihjqxg
umdryvbvlapgozfrtwcnihjqxg
umdrkebvlapkozfstwcnihihxg
umdryebvrppkozfsowcnihjqxg
umdryebvlapktzfsdwclihjqxg
otdrdebvlapkozfstwcnihjqxg
mmdryebvlazkozfxtwcnihjqxg
umdryebvlapkozfsbwtnihjqxa
imqryebvrapkozfstwcnihjqxg
umdryebvlrpkozfscwcnihjqlg
uedryebvlapkoznsvwcnihjqxg
umdryebvlqpkozfstscnihjqxj
umerycbvlapkozfstwcnihjqxh
umdkykbvlapjozfstwcnihjqxg'''

ids = data.splitlines()

def exactly(identity, count):
    for letter in identity:
        if identity.count(letter) == count:
            return True
    return False

exactly2 = sum(exactly(identity, 2) for identity in ids)
exactly3 = sum(exactly(identity, 3) for identity in ids)
checksum = exactly2 * exactly3
print(checksum)

from difflib import get_close_matches

def diffby1(a, b):
    diffs = sum(m != n for m, n in zip(a, b))
    return diffs == 1

def match(ids):
    solutions = []
    for identity in ids.copy():
        ids.remove(identity)
        try:
            closest = get_close_matches(identity, ids, 1)[0]
        except IndexError:
            continue
        if diffby1(identity, closest):
            solutions.append((identity, closest))
    return solutions

matched = match(ids)
#print(matched)

common = ''.join(m for m, n in zip(*matched[0]) if m == n)
print(common)
