from collections import defaultdict

raw_codon_table = """
UUU F      CUU L      AUU I      GUU V
UUC F      CUC L      AUC I      GUC V
UUA L      CUA L      AUA I      GUA V
UUG L      CUG L      AUG M      GUG V
UCU S      CCU P      ACU T      GCU A
UCC S      CCC P      ACC T      GCC A
UCA S      CCA P      ACA T      GCA A
UCG S      CCG P      ACG T      GCG A
UAU Y      CAU H      AAU N      GAU D
UAC Y      CAC H      AAC N      GAC D
UAA Stop   CAA Q      AAA K      GAA E
UAG Stop   CAG Q      AAG K      GAG E
UGU C      CGU R      AGU S      GGU G
UGC C      CGC R      AGC S      GGC G
UGA Stop   CGA R      AGA R      GGA G
UGG W      CGG R      AGG R      GGG G
"""
codondict = {}
codon_table_split = raw_codon_table.split()
codons = codon_table_split[::2]
aas = codon_table_split[1::2]
for codon, aa in zip(codons, aas):
	codondict[codon] = aa
print(codondict)
print()
freqdict = defaultdict(int)
for k,v in codondict.items():
	freqdict[v] += 1
print(freqdict)

def mRNA(protein):
	possible_mRNA_strings = 3
	for aa in protein:
		possible_mRNA_strings *= freqdict[aa]
	return possible_mRNA_strings % 1000000

print(mRNA("MMQMKNGVIQVGNIWRWIQHTNSSMGIKYAWQFCIQTVCGFAKFVTKIYLPNVPGPSWKQAYRNVCMHSTGEFLLVQFMQDWTPWFKTNCHGRLQGPYCHNYCTDTNKEKNYYLVYPEVALIQLFCWQPNYGTCECIHKRRRIKYQPVHSCWWNADWDMYDDSSSWVIVDYNKIPPLALNTWIDHNERHCIYHVTKQHMHWLYEYIMLYMGITKRQLYNHCDHHWNWMIFSRRMQSEEDSAVLLSMQMQKMIFCVEHYLLIEKNSLFEACGCMHLRTHMGFMTPLRVAEIRRTHFPISCPWWLTFKKDIQGMPMESLQGWTSSIYYSVVYKSINYCSTHNKMQLCWGIQKYRTDMWCDMLKTDICVRCCSNKQFIWDSTLVCIHCRDTNSYFFRNRGSEENHITECARGAHCYYFHRRDHACEDSTYCAVPDWDTKHCPVYIGDQELPMDIVELKMGLVNLPWTRHCPSVYKPPGSVSAWPWWMVVGYDGYGRHTYGTIDDYILLLPYQAYRSSRVEYQIGNNWKCHSDKRTTEDWWWVMNCIIRYQATEMISMNLEHDTEQYNMTFCYCRIAAWMMRFHIKWIDTHKAEWCCWLLGVKVREKQHAMDFGMWSQQFLCWNEPMCTGASDFAGSCEHIHVSNCHYGPSGCSRPQEMGLMFPVCHRCEDIMALDKVTDTCNTFYMWMADGYRDFKQANLYKKCAAIANSPDTWMSRVHMYNIMNIGRMLSRSPCGDWKDIRGYNATTCTSAHKINKKNDWNAYNHQNCRQDECTQWTEWHHWWFTWKYYFHHWIVIRQWVMDWRGRPEPIQPHARYMQAHYHIKNPKCIVAFVFDQEWVYHECIIIAYIHEVLKRANSHFEPGVKMMQRGSYELNHMSASAWIQHQGMALETKDRTEREWQLVIFTYAWARMEDCRSILIGLFICWKIHSDVMRCKCLKMWRYPWTFVMEAWRIPQLNYGQMWVSCYTMAFCSSASAPFFACFQGNSNFHAWMTRQCQFD"))
