DNA_codon_table = """
TTT F      CTT L      ATT I      GTT V
TTC F      CTC L      ATC I      GTC V
TTA L      CTA L      ATA I      GTA V
TTG L      CTG L      ATG M      GTG V
TCT S      CCT P      ACT T      GCT A
TCC S      CCC P      ACC T      GCC A
TCA S      CCA P      ACA T      GCA A
TCG S      CCG P      ACG T      GCG A
TAT Y      CAT H      AAT N      GAT D
TAC Y      CAC H      AAC N      GAC D
TAA Stop   CAA Q      AAA K      GAA E
TAG Stop   CAG Q      AAG K      GAG E
TGT C      CGT R      AGT S      GGT G
TGC C      CGC R      AGC S      GGC G
TGA Stop   CGA R      AGA R      GGA G
TGG W      CGG R      AGG R      GGG G 
"""
codon_table_split = DNA_codon_table.split()
TABLE = dict(zip(codon_table_split[::2], codon_table_split[1::2]))

def orf(DNA):
	def check3frames(DNA):
		proteins = set()
		for frame in range(3):
			protein = ""
			while frame <= len(DNA)-3:
				codon = DNA[frame:frame+3]
				if protein == "" and codon != "ATG":
					frame += 3
					continue
				protein += TABLE[codon]
				frame += 3
			while "M" in protein:
				start = protein.index("M")
				try:
					stop = protein.index("Stop",start)
				except ValueError:
					break
				proteins.add(protein[start:stop])
				protein = protein[start+1:]
		return proteins
	def cDNA(DNA):
		cDNA_dict = {"A":"T", "T":"A", "C":"G", "G":"C"}
		cDNA = ""
		for nt in DNA[::-1]:
			cDNA += cDNA_dict[nt]
		return cDNA
	return check3frames(DNA) | check3frames(cDNA(DNA))

given = """TGGGCCTGTTTGCCCCGTAGTGCGAATTGCTCCTGTCGGGCCCGAGTTATTTATTTTAAT
AGGTGGTGGCAGTACTTTAACCTTCCGACTTTTATAAGCGATCGGATCCACTGACAGAGG
GGGACTCTTTTCCAGGAAAACGTCAGATTGAACGTGTATGGCCAACGATCGCGGCGAGGT
TTCTGACCCCTCGTAAATTGCTTTGCCATAAGAACAAGGCCCATGACGCTGAGGGGAGCT
ATTTAGGAAACTTTATCTCCCTGACGAAGAGCAGTGCGATAGGCCCGTTGATGGCCTGAC
CGTCCATCCGACACGTGCTATTTGTGCCTGCAGTATGTGTTGCAAGACGGCAACTTCAAA
TAACTGCTAATTCTCAAGGCCCCCGGAATTGAGTGGGTCGTCTGTCAAGGAGCTTTGTGC
CGCCTAAGCATTCCTCCCTAAGATCAGGACCCCCACGCAATAATGGCGGGTAATATTCCG
GACAGGAGTTGGTAGCTACCAACTCCTGTCCGGAATATTACCCGCCATTTCGTGACCTGA
TGGACTTTAATCTTGACTGAGATGTTCATTTAAAGTGTCATATAACACCTCAAAGCGGCC
AGGTATTAATATGGGGGCTCTGCTAACGTACGGTCTCCCAGAGACAACTGGGGTCGAGCC
TCCCGGTTACCCTTTATACCGCAGTTTGTCTCGGAAGTTTGTCAGGTGCAAGGATTGCCG
TCCTCTTTGGTATACGTTAATCTTTGCGCGCGCGAGTTGAACACTTCTGTTCAACGTGCA
GAATCGCGTTTCCCTGTTCCCCGCTTCACAGCCACTGTAAACTGGCGGCCACCGCCTTTA
CGCGGCTCGGTCGTTCCGTTACGACGCCGATCCAGAACAAGAGTGTATACTGTAATACCT
AGTTATATCAGTCATGTTGTGGCGGGAGCTCTGTGGTCCTGTAGGGCCGAGAGCGCTAGA
ATTGTTGTCGCTAAGGAAATGCCTGGCAAC""".replace("\n","")

for protein in orf(given):
	print(protein)
